spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/Niddu?useSSL=false&serverTimezone=UTC #Name de la BD de panas :v
spring.datasource.username=root
spring.datasource.password=qwerty #Pass despues lo dejo como variable de entorno xd
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
