spring.application.name=demo

#Name de la bd de panas :v
spring.datasource.url=jdbc:mysql://mysql-robber-2025.mysql.database.azure.com:3306/Niddu?useSSL=true&verifyServerCertificate=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=ElTreintayOcho
spring.datasource.password=Password456*

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect