name: Verificar sintaxis SQL

on:
  push:
    branches:
      - database
    paths:
      - "**.sql"
  workflow_dispatch:

jobs:
  check-syntax:
    name: Validación de sintaxis MySQL
    runs-on: ubuntu-latest

    permissions:
      contents: read

    services:
      mysql:
        image: mysql:8.2
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -proot"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=10

    steps:
      - name: Clonar repositorio (rama database)
        uses: actions/checkout@v4
        with:
          ref: database

      - name: Esperando que MySQL inicie
        shell: bash
        run: |
          echo "Esperando a que MySQL inicie..."
          for i in {1..15}; do
            if mysqladmin ping -h 127.0.0.1 -proot --silent; then
              echo "MySQL está listo."
              break
            fi
            echo "Intento $i/15: esperando..."
            sleep 4
          done

      - name: Verificar sintaxis del archivo BD_Niddu.sql
        shell: bash
        run: |
          echo "Verificando sintaxis de BD_Niddu.sql..."
          mysql -h 127.0.0.1 -uroot -proot < BD_Niddu.sql
          echo "Verificacin completada correctamente."
